"""
Exercise database — 270 exercises from the Resistance Training Planner.
Columns: id, muscle_group, name, level, body_region, push_pull, modality, joint_type

Modality codes:
  FW = Free Weights (dumbbells, barbells, bodyweight)
  C  = Cables
  M  = Machine
  BW = Bodyweight only (subset of FW — no equipment needed)

Level: Beginner / Intermediate / Advanced
Body region: Upper / Lower / Core
Push_pull: Push / Pull / Static
Joint type: M (multi-joint) / S (single-joint)
"""

# Equipment category → which modalities are available
EQUIPMENT_MODALITY_MAP = {
    "gym":          ["FW", "C", "M", "BW"],
    "dumbbells":    ["FW", "BW"],
    "barbell":      ["FW", "BW"],
    "cables":       ["C", "BW"],
    "machine":      ["M", "BW"],
    "bodyweight":   ["BW"],
    "resistance_bands": ["FW", "BW"],
    "kettlebell":   ["FW", "BW"],
}

# Exercises that require NO equipment (pure bodyweight)
BODYWEIGHT_EXERCISES = {
    "Full Reverse Crunch", "Reverse Crunch", "Alternating Heel Touch", "Cross Crunch",
    "Seated Medicine Ball Twist", "Front Plank (from knees)", "Front Plank (from toes)",
    "Side-Plank (from knees)", "Side-Plank (hip lift)", "Side-Plank (from toes)",
    "V-Up", "Bent Knee Sit-Up", "Bent-Knee Crunch", "Crunch", "Heel Touch", "Sit-Up",
    "Assisted Pull-Up", "Pull-Up", "Reverse-Grip Pull-Up", "V-Bar Pull-Up", "Inverted Pull-Up",
    "Push-Up", "Wide Push-Up", "Narrow Push-Up", "Decline Push-Up", "Diamond Push-Up",
    "Dips", "Forward Lean Dips",
    "Bent-Knee Single-Leg Hip Lift", "Elevated Hip Lift", "Hip Lift",
    "Bodyweight Squat", "Jump Squat", "Walking Lunge", "Reverse Lunge", "Step-Up",
    "Alternating Superman", "Quadruped Alternating Superman", "Back Raise",
    "Glute Kickback", "Donkey Calf Raise",
}

EXERCISE_DB = [
    # ── Abdominals - Lower ──
    {"id": 1,  "muscle_group": "Abdominals - Lower",   "name": "Full Reverse Crunch",                    "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 2,  "muscle_group": "Abdominals - Lower",   "name": "Incline Hip Thrust",                     "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 3,  "muscle_group": "Abdominals - Lower",   "name": "Incline Reverse Crunch",                 "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 4,  "muscle_group": "Abdominals - Lower",   "name": "Lying Hip Thrust",                       "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 5,  "muscle_group": "Abdominals - Lower",   "name": "Reverse Crunch",                         "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 6,  "muscle_group": "Abdominals - Lower",   "name": "Reverse Medicine Ball Crunch",           "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    # ── Abdominals - Obliques ──
    {"id": 7,  "muscle_group": "Abdominals - Obliques","name": "Alternating Heel Touch",                 "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 8,  "muscle_group": "Abdominals - Obliques","name": "Bent-Knee Medicine Ball Hip Rotation",   "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 9,  "muscle_group": "Abdominals - Obliques","name": "Cable Chop",                             "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "C",  "joint_type": "M"},
    {"id": 10, "muscle_group": "Abdominals - Obliques","name": "Cross Crunch",                           "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 11, "muscle_group": "Abdominals - Obliques","name": "Cross Crunch w/ Medicine Ball",          "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 12, "muscle_group": "Abdominals - Obliques","name": "Decline Cross Sit-Up",                   "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 13, "muscle_group": "Abdominals - Obliques","name": "Decline Sit-Up w/ Twist",                "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 14, "muscle_group": "Abdominals - Obliques","name": "Reverse Cable Chop",                     "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "C",  "joint_type": "M"},
    {"id": 15, "muscle_group": "Abdominals - Obliques","name": "Seated Medicine Ball Twist",             "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 16, "muscle_group": "Abdominals - Obliques","name": "Trunk Rotator",                          "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    # ── Abdominals - Total ──
    {"id": 17, "muscle_group": "Abdominals - Total",   "name": "Front Plank (from knees)",               "level": "Beginner",     "body_region": "Core",  "push_pull": "Static", "modality": "FW", "joint_type": "M"},
    {"id": 18, "muscle_group": "Abdominals - Total",   "name": "Front Plank (from toes)",                "level": "Intermediate", "body_region": "Core",  "push_pull": "Static", "modality": "FW", "joint_type": "M"},
    {"id": 19, "muscle_group": "Abdominals - Total",   "name": "Front Plank (tripod)",                   "level": "Advanced",     "body_region": "Core",  "push_pull": "Static", "modality": "FW", "joint_type": "M"},
    {"id": 20, "muscle_group": "Abdominals - Total",   "name": "Side-Plank (from knees)",                "level": "Intermediate", "body_region": "Core",  "push_pull": "Static", "modality": "FW", "joint_type": "M"},
    {"id": 21, "muscle_group": "Abdominals - Total",   "name": "Side-Plank (hip lift)",                  "level": "Beginner",     "body_region": "Core",  "push_pull": "Static", "modality": "FW", "joint_type": "M"},
    {"id": 22, "muscle_group": "Abdominals - Total",   "name": "Side-Plank (from toes)",                 "level": "Advanced",     "body_region": "Core",  "push_pull": "Static", "modality": "FW", "joint_type": "M"},
    {"id": 23, "muscle_group": "Abdominals - Total",   "name": "Ab Cycle",                               "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 24, "muscle_group": "Abdominals - Total",   "name": "Kneeling Ab Rollout",                    "level": "Intermediate", "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 25, "muscle_group": "Abdominals - Total",   "name": "Medicine Ball V-Up",                     "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 26, "muscle_group": "Abdominals - Total",   "name": "V-Up",                                   "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 27, "muscle_group": "Abdominals - Total",   "name": "Weighted V-Up",                          "level": "Intermediate", "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    # ── Abdominals - Upper ──
    {"id": 28, "muscle_group": "Abdominals - Upper",   "name": "Bent Knee Sit-Up",                       "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 29, "muscle_group": "Abdominals - Upper",   "name": "Bent-Knee Crunch",                       "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 30, "muscle_group": "Abdominals - Upper",   "name": "Crunch",                                 "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 31, "muscle_group": "Abdominals - Upper",   "name": "Decline Crunch",                         "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 32, "muscle_group": "Abdominals - Upper",   "name": "Decline Sit-Up",                         "level": "Advanced",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 33, "muscle_group": "Abdominals - Upper",   "name": "Heel Touch",                             "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 34, "muscle_group": "Abdominals - Upper",   "name": "Sit-Up",                                 "level": "Beginner",     "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 35, "muscle_group": "Abdominals - Upper",   "name": "Weighted Crunch",                        "level": "Intermediate", "body_region": "Core",  "push_pull": "Push",   "modality": "FW", "joint_type": "M"},
    {"id": 36, "muscle_group": "Abdominals - Upper",   "name": "Cable Crunch",                           "level": "Intermediate", "body_region": "Core",  "push_pull": "Push",   "modality": "C",  "joint_type": "M"},
    # ── Back - Latissimus Dorsi ──
    {"id": 37, "muscle_group": "Back - Latissimus Dorsi",     "name": "Assisted Pull-Up",               "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 38, "muscle_group": "Back - Latissimus Dorsi",     "name": "Close-Grip Lat Pulldown",        "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "M",  "joint_type": "M"},
    {"id": 39, "muscle_group": "Back - Latissimus Dorsi",     "name": "Inverted Pull-Up",               "level": "Advanced",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 40, "muscle_group": "Back - Latissimus Dorsi",     "name": "Lat Pulldown",                   "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 41, "muscle_group": "Back - Latissimus Dorsi",     "name": "Pull-Up",                        "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 42, "muscle_group": "Back - Latissimus Dorsi",     "name": "Reverse-Grip Lat Pulldown",      "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 43, "muscle_group": "Back - Latissimus Dorsi",     "name": "Reverse-Grip Pull-Up",           "level": "Advanced",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 44, "muscle_group": "Back - Latissimus Dorsi",     "name": "V-Bar Pull-Up",                  "level": "Advanced",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 45, "muscle_group": "Back - Latissimus Dorsi",     "name": "Wide-Grip Lat Pulldown",         "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    # ── Back - Lat.Dorsi/Rhomboids ──
    {"id": 46, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Bent-Over Alternating Dumbbell Row", "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull", "modality": "FW", "joint_type": "M"},
    {"id": 47, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Bent-Over Barbell Row",          "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 48, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Bent-Over Dumbbell Row",         "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 49, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Bent-Over Hammer Dumbbell Row",  "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 50, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Bent-Over Long Barbell Row",     "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 51, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Cable Row",                      "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 52, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Close-Grip Cable Row",           "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 53, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Dumbbell Deadlift Row",          "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 54, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Machine Row",                    "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "M",  "joint_type": "M"},
    {"id": 55, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "One-Arm Cable Row",              "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 56, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "One-Arm Dumbbell Row",           "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 57, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Reverse-Grip Barbell Row",       "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 58, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Seated Cable Row",               "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 59, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "T-Bar Row",                      "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    {"id": 60, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Wide-Grip Cable Row",            "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 61, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Wide-Grip Machine Row",          "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",   "modality": "M",  "joint_type": "M"},
    {"id": 62, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Wide-Grip Seated Cable Row",     "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "C",  "joint_type": "M"},
    {"id": 63, "muscle_group": "Back - Lat.Dorsi/Rhomboids",  "name": "Incline Dumbbell Row",           "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",   "modality": "FW", "joint_type": "M"},
    # ── Biceps ──
    {"id": 64, "muscle_group": "Biceps",  "name": "Alternating Dumbbell Curl",              "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 65, "muscle_group": "Biceps",  "name": "Alternating Hammer Curl",                "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 66, "muscle_group": "Biceps",  "name": "Barbell Curl",                           "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 67, "muscle_group": "Biceps",  "name": "Cable Curl",                             "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 68, "muscle_group": "Biceps",  "name": "Close-Grip Barbell Curl",                "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 69, "muscle_group": "Biceps",  "name": "Concentration Curl",                     "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 70, "muscle_group": "Biceps",  "name": "Dumbbell Curl",                          "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 71, "muscle_group": "Biceps",  "name": "EZ Bar Curl",                            "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 72, "muscle_group": "Biceps",  "name": "Hammer Curl",                            "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 73, "muscle_group": "Biceps",  "name": "High Cable Curl",                        "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 74, "muscle_group": "Biceps",  "name": "Incline Dumbbell Curl",                  "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 75, "muscle_group": "Biceps",  "name": "Machine Curl",                           "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "M",  "joint_type": "S"},
    {"id": 76, "muscle_group": "Biceps",  "name": "One-Arm Cable Curl",                     "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 77, "muscle_group": "Biceps",  "name": "One-Arm Dumbbell Preacher Curl",         "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 78, "muscle_group": "Biceps",  "name": "Preacher Curl",                          "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 79, "muscle_group": "Biceps",  "name": "Resistance Band Curl",                   "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 80, "muscle_group": "Biceps",  "name": "Reverse Barbell Curl",                   "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 81, "muscle_group": "Biceps",  "name": "Reverse Cable Curl",                     "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 82, "muscle_group": "Biceps",  "name": "Seated Alternating Dumbbell Curl",       "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 83, "muscle_group": "Biceps",  "name": "Seated Dumbbell Curl",                   "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 84, "muscle_group": "Biceps",  "name": "Seated EZ Bar Curl",                     "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 85, "muscle_group": "Biceps",  "name": "Standing Barbell Curl",                  "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 86, "muscle_group": "Biceps",  "name": "Wide-Grip Barbell Curl",                 "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 87, "muscle_group": "Biceps",  "name": "Zottman Curl",                           "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 88, "muscle_group": "Biceps",  "name": "Spider Curl",                            "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 89, "muscle_group": "Biceps",  "name": "Cable Hammer Curl",                      "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 90, "muscle_group": "Biceps",  "name": "Drag Curl",                              "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 91, "muscle_group": "Biceps",  "name": "Scott Curl",                             "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 92, "muscle_group": "Biceps",  "name": "Cross Body Hammer Curl",                 "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 93, "muscle_group": "Biceps",  "name": "Chin-Up",                                "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    {"id": 94, "muscle_group": "Biceps",  "name": "Neutral Grip Pull-Up",                   "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    {"id": 95, "muscle_group": "Biceps",  "name": "Cable Concentration Curl",               "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 96, "muscle_group": "Biceps",  "name": "TRX Curl",                               "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 97, "muscle_group": "Biceps",  "name": "Bayesian Curl",                          "level": "Advanced",     "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 98, "muscle_group": "Biceps",  "name": "Flexion 21s",                            "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 99, "muscle_group": "Biceps",  "name": "Overhead Cable Curl",                    "level": "Advanced",     "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 100,"muscle_group": "Biceps",  "name": "Supine Barbell Curl",                    "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 101,"muscle_group": "Biceps",  "name": "Low-Pulley Curl",                        "level": "Beginner",     "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    # ── Calves - Gastrocnemius ──
    {"id": 102,"muscle_group": "Calves - Gastrocnemius","name": "Barbell Calf Raise",       "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 103,"muscle_group": "Calves - Gastrocnemius","name": "Calf Press",               "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 104,"muscle_group": "Calves - Gastrocnemius","name": "Calf Raise - Seated",      "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 105,"muscle_group": "Calves - Gastrocnemius","name": "Calf Raise on Leg Press",  "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 106,"muscle_group": "Calves - Gastrocnemius","name": "Dumbbell Calf Raise",      "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 107,"muscle_group": "Calves - Gastrocnemius","name": "Single-Leg Calf Raise",    "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 108,"muscle_group": "Calves - Gastrocnemius","name": "Standing Calf Raise",      "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 109,"muscle_group": "Calves - Gastrocnemius","name": "Donkey Calf Raise",        "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    # ── Calves - Soleus ──
    {"id": 110,"muscle_group": "Calves - Soleus",  "name": "Seated Calf Raise",             "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 111,"muscle_group": "Calves - Soleus",  "name": "Seated Single-Leg Calf Raise",  "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    # ── Chest - Pectoralis ──
    {"id": 112,"muscle_group": "Chest - Pectoralis","name": "Alternating Dumbbell Bench Press","level": "Intermediate","body_region": "Upper","push_pull": "Push",  "modality": "FW","joint_type": "M"},
    {"id": 113,"muscle_group": "Chest - Pectoralis","name": "Barbell Bench Press",          "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 114,"muscle_group": "Chest - Pectoralis","name": "Cable Chest Press",            "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "M"},
    {"id": 115,"muscle_group": "Chest - Pectoralis","name": "Cable Crossover",              "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 116,"muscle_group": "Chest - Pectoralis","name": "Cable Fly",                    "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 117,"muscle_group": "Chest - Pectoralis","name": "Chest Press",                  "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 118,"muscle_group": "Chest - Pectoralis","name": "Close-Grip Dumbbell Bench Press","level": "Intermediate","body_region": "Upper","push_pull": "Push",  "modality": "FW","joint_type": "M"},
    {"id": 119,"muscle_group": "Chest - Pectoralis","name": "Decline Barbell Bench Press",  "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 120,"muscle_group": "Chest - Pectoralis","name": "Decline Dumbbell Bench Press", "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 121,"muscle_group": "Chest - Pectoralis","name": "Decline Dumbbell Fly",         "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 122,"muscle_group": "Chest - Pectoralis","name": "Dips",                         "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 123,"muscle_group": "Chest - Pectoralis","name": "Dumbbell Bench Press",         "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 124,"muscle_group": "Chest - Pectoralis","name": "Dumbbell Fly",                 "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 125,"muscle_group": "Chest - Pectoralis","name": "Dumbbell Pullover",            "level": "Intermediate", "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 126,"muscle_group": "Chest - Pectoralis","name": "Incline Barbell Bench Press",  "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 127,"muscle_group": "Chest - Pectoralis","name": "Incline Cable Fly",            "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 128,"muscle_group": "Chest - Pectoralis","name": "Incline Dumbbell Bench Press", "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 129,"muscle_group": "Chest - Pectoralis","name": "Incline Dumbbell Fly",         "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 130,"muscle_group": "Chest - Pectoralis","name": "Pec Deck Fly",                 "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 131,"muscle_group": "Chest - Pectoralis","name": "Push-Up",                      "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 132,"muscle_group": "Chest - Pectoralis","name": "Wide Push-Up",                 "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 133,"muscle_group": "Chest - Pectoralis","name": "Decline Push-Up",              "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 134,"muscle_group": "Chest - Pectoralis","name": "Diamond Push-Up",              "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 135,"muscle_group": "Chest - Pectoralis","name": "Low-to-High Cable Fly",        "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 136,"muscle_group": "Chest - Pectoralis","name": "High-to-Low Cable Fly",        "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 137,"muscle_group": "Chest - Pectoralis","name": "Svend Press",                  "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 138,"muscle_group": "Chest - Pectoralis","name": "Guillotine Press",             "level": "Advanced",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 139,"muscle_group": "Chest - Pectoralis","name": "Landmine Press",               "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 140,"muscle_group": "Chest - Pectoralis","name": "Loaded Stretch Fly",           "level": "Advanced",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 141,"muscle_group": "Chest - Pectoralis","name": "Smith Machine Bench Press",    "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 142,"muscle_group": "Chest - Pectoralis","name": "Floor Press",                  "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 143,"muscle_group": "Chest - Pectoralis","name": "Plyometric Push-Up",           "level": "Advanced",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 144,"muscle_group": "Chest - Pectoralis","name": "Band-Resisted Push-Up",        "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 145,"muscle_group": "Chest - Pectoralis","name": "Resistance Band Chest Press",  "level": "Beginner",     "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 146,"muscle_group": "Chest - Pectoralis","name": "Cable Crossover (Neutral Grip)","level": "Intermediate","body_region": "Upper","push_pull": "Push",   "modality": "C",  "joint_type": "S"},
    {"id": 147,"muscle_group": "Chest - Pectoralis","name": "Hex Press",                    "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 148,"muscle_group": "Chest - Pectoralis","name": "Narrow Barbell Bench Press",   "level": "Intermediate", "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    # ── Legs - Hamstrings ──
    {"id": 149,"muscle_group": "Legs - Hamstrings","name": "Bent-Knee Single-Leg Hip Lift", "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 150,"muscle_group": "Legs - Hamstrings","name": "Elevated Hip Lift",             "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 151,"muscle_group": "Legs - Hamstrings","name": "Elevated Single-Leg Hip Lift",  "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 152,"muscle_group": "Legs - Hamstrings","name": "Hip Lift",                      "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 153,"muscle_group": "Legs - Hamstrings","name": "Lying Leg Curl",                "level": "Beginner",     "body_region": "Lower", "push_pull": "Pull",  "modality": "M",  "joint_type": "S"},
    {"id": 154,"muscle_group": "Legs - Hamstrings","name": "Romanian Deadlift",             "level": "Beginner",     "body_region": "Lower", "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    {"id": 155,"muscle_group": "Legs - Hamstrings","name": "Seated Leg Curl",               "level": "Beginner",     "body_region": "Lower", "push_pull": "Pull",  "modality": "M",  "joint_type": "S"},
    {"id": 156,"muscle_group": "Legs - Hamstrings","name": "Standing Leg Curl",             "level": "Intermediate", "body_region": "Lower", "push_pull": "Pull",  "modality": "M",  "joint_type": "S"},
    {"id": 157,"muscle_group": "Legs - Hamstrings","name": "Stiff-Leg Deadlift",            "level": "Intermediate", "body_region": "Lower", "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    {"id": 158,"muscle_group": "Legs - Hamstrings","name": "Nordic Curl",                   "level": "Advanced",     "body_region": "Lower", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 159,"muscle_group": "Legs - Hamstrings","name": "Cable Pull-Through",            "level": "Beginner",     "body_region": "Lower", "push_pull": "Pull",  "modality": "C",  "joint_type": "M"},
    # ── Legs - Quadriceps ──
    {"id": 160,"muscle_group": "Legs - Quadriceps","name": "Barbell Diagonal Lunge",        "level": "Advanced",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 161,"muscle_group": "Legs - Quadriceps","name": "Barbell Hack Squat",            "level": "Advanced",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 162,"muscle_group": "Legs - Quadriceps","name": "Barbell Lunge",                 "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 163,"muscle_group": "Legs - Quadriceps","name": "Barbell Squat",                 "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 164,"muscle_group": "Legs - Quadriceps","name": "Barbell Step-Up",               "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 165,"muscle_group": "Legs - Quadriceps","name": "Bulgarian Split Squat",         "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 166,"muscle_group": "Legs - Quadriceps","name": "Deadlift",                      "level": "Beginner",     "body_region": "Lower", "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    {"id": 167,"muscle_group": "Legs - Quadriceps","name": "Dumbbell Lunge",                "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 168,"muscle_group": "Legs - Quadriceps","name": "Dumbbell Squat",                "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 169,"muscle_group": "Legs - Quadriceps","name": "Dumbbell Step-Up",              "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 170,"muscle_group": "Legs - Quadriceps","name": "Front Squat",                   "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 171,"muscle_group": "Legs - Quadriceps","name": "Goblet Squat",                  "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 172,"muscle_group": "Legs - Quadriceps","name": "Hack Squat Machine",            "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 173,"muscle_group": "Legs - Quadriceps","name": "Lateral Lunge",                 "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 174,"muscle_group": "Legs - Quadriceps","name": "Leg Extension",                 "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 175,"muscle_group": "Legs - Quadriceps","name": "Leg Press",                     "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 176,"muscle_group": "Legs - Quadriceps","name": "Pistol Squat",                  "level": "Advanced",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 177,"muscle_group": "Legs - Quadriceps","name": "Reverse Lunge",                 "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 178,"muscle_group": "Legs - Quadriceps","name": "Romanian Squat",                "level": "Advanced",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 179,"muscle_group": "Legs - Quadriceps","name": "Sissy Squat",                   "level": "Advanced",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 180,"muscle_group": "Legs - Quadriceps","name": "Smith Machine Squat",           "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 181,"muscle_group": "Legs - Quadriceps","name": "Sumo Squat",                    "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 182,"muscle_group": "Legs - Quadriceps","name": "Walking Lunge",                 "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 183,"muscle_group": "Legs - Quadriceps","name": "Jump Squat",                    "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 184,"muscle_group": "Legs - Quadriceps","name": "Box Squat",                     "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 185,"muscle_group": "Legs - Quadriceps","name": "Pause Squat",                   "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 186,"muscle_group": "Legs - Quadriceps","name": "Close-Stance Squat",            "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 187,"muscle_group": "Legs - Quadriceps","name": "Wide-Stance Squat",             "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 188,"muscle_group": "Legs - Quadriceps","name": "Step-Up",                       "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 189,"muscle_group": "Legs - Quadriceps","name": "Bodyweight Squat",              "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 190,"muscle_group": "Legs - Quadriceps","name": "Split Squat",                   "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 191,"muscle_group": "Legs - Quadriceps","name": "Zercher Squat",                 "level": "Advanced",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 192,"muscle_group": "Legs - Quadriceps","name": "Safety Bar Squat",              "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 193,"muscle_group": "Legs - Quadriceps","name": "Landmine Squat",                "level": "Beginner",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 194,"muscle_group": "Legs - Quadriceps","name": "Curtsy Lunge",                  "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 195,"muscle_group": "Legs - Quadriceps","name": "Trap Bar Deadlift",             "level": "Beginner",     "body_region": "Lower", "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    {"id": 196,"muscle_group": "Legs - Quadriceps","name": "Jumping Lunge",                 "level": "Advanced",     "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 197,"muscle_group": "Legs - Quadriceps","name": "Single-Leg Press",              "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 198,"muscle_group": "Legs - Quadriceps","name": "Pendulum Squat",               "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 199,"muscle_group": "Legs - Quadriceps","name": "Wall Sit",                      "level": "Beginner",     "body_region": "Lower", "push_pull": "Static","modality": "FW", "joint_type": "S"},
    {"id": 200,"muscle_group": "Legs - Quadriceps","name": "Cossack Squat",                 "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 201,"muscle_group": "Legs - Quadriceps","name": "High-Bar Back Squat",           "level": "Intermediate", "body_region": "Lower", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    # ── Lower Back - Erector Spinae ──
    {"id": 202,"muscle_group": "Lower Back - Erector Spinae","name": "Alternating Superman", "level": "Beginner",    "body_region": "Core",  "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 203,"muscle_group": "Lower Back - Erector Spinae","name": "Back Raise",           "level": "Beginner",    "body_region": "Core",  "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 204,"muscle_group": "Lower Back - Erector Spinae","name": "Quadruped Alternating Superman","level": "Beginner","body_region": "Core","push_pull": "Pull","modality": "FW","joint_type": "S"},
    {"id": 205,"muscle_group": "Lower Back - Erector Spinae","name": "Reverse Hyper",        "level": "Intermediate","body_region": "Core",  "push_pull": "Pull",  "modality": "M",  "joint_type": "S"},
    {"id": 206,"muscle_group": "Lower Back - Erector Spinae","name": "Good Morning",         "level": "Intermediate","body_region": "Core",  "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    # ── Shoulders - Delts/Traps ──
    {"id": 207,"muscle_group": "Shoulders - Delts/Traps","name": "Arnold Dumbbell Press",    "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 208,"muscle_group": "Shoulders - Delts/Traps","name": "Barbell Shoulder Press",   "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 209,"muscle_group": "Shoulders - Delts/Traps","name": "Dumbbell Alternating Shoulder Press","level":"Intermediate","body_region":"Upper","push_pull":"Push","modality":"FW","joint_type":"M"},
    {"id": 210,"muscle_group": "Shoulders - Delts/Traps","name": "Dumbbell Front Raise",     "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 211,"muscle_group": "Shoulders - Delts/Traps","name": "Dumbbell Lateral Raise",   "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 212,"muscle_group": "Shoulders - Delts/Traps","name": "Dumbbell Rear Delt Fly",   "level": "Beginner",    "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "S"},
    {"id": 213,"muscle_group": "Shoulders - Delts/Traps","name": "Dumbbell Shoulder Press",  "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 214,"muscle_group": "Shoulders - Delts/Traps","name": "Dumbbell Shrug",           "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 215,"muscle_group": "Shoulders - Delts/Traps","name": "Face Pull",                "level": "Beginner",    "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 216,"muscle_group": "Shoulders - Delts/Traps","name": "Front Plate Raise",        "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 217,"muscle_group": "Shoulders - Delts/Traps","name": "Lateral Raise Machine",    "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 218,"muscle_group": "Shoulders - Delts/Traps","name": "Machine Shoulder Press",   "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 219,"muscle_group": "Shoulders - Delts/Traps","name": "Military Press",           "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 220,"muscle_group": "Shoulders - Delts/Traps","name": "Overhead Press",           "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 221,"muscle_group": "Shoulders - Delts/Traps","name": "Reverse Cable Fly",        "level": "Intermediate","body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    {"id": 222,"muscle_group": "Shoulders - Delts/Traps","name": "Reverse Fly",              "level": "Beginner",    "body_region": "Upper", "push_pull": "Pull",  "modality": "M",  "joint_type": "S"},
    {"id": 223,"muscle_group": "Shoulders - Delts/Traps","name": "Seated Barbell Shoulder Press","level": "Beginner","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 224,"muscle_group": "Shoulders - Delts/Traps","name": "Seated Dumbbell Shoulder Press","level": "Beginner","body_region": "Upper","push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 225,"muscle_group": "Shoulders - Delts/Traps","name": "Upright Row",              "level": "Beginner",    "body_region": "Upper", "push_pull": "Pull",  "modality": "FW", "joint_type": "M"},
    {"id": 226,"muscle_group": "Shoulders - Delts/Traps","name": "Cable Lateral Raise",      "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 227,"muscle_group": "Shoulders - Delts/Traps","name": "Cable Front Raise",        "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 228,"muscle_group": "Shoulders - Delts/Traps","name": "Push Press",               "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 229,"muscle_group": "Shoulders - Delts/Traps","name": "Bradford Press",           "level": "Advanced",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 230,"muscle_group": "Shoulders - Delts/Traps","name": "Lu Raise",                 "level": "Advanced",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 231,"muscle_group": "Shoulders - Delts/Traps","name": "Landmine Press (Shoulder)","level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    # ── Shoulders - Rotator Cuff ──
    {"id": 232,"muscle_group": "Shoulders - Rotator Cuff","name": "Cable External Rotation", "level": "Beginner",    "body_region": "Upper", "push_pull": "Pull",  "modality": "C",  "joint_type": "S"},
    # ── Triceps ──
    {"id": 233,"muscle_group": "Triceps","name": "Close-Grip Bench Press",                   "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 234,"muscle_group": "Triceps","name": "Forward Lean Dips",                        "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 235,"muscle_group": "Triceps","name": "Assisted Dips",                            "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 236,"muscle_group": "Triceps","name": "Cable Overhead Tricep Extension",          "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 237,"muscle_group": "Triceps","name": "Cable Tricep Pushdown",                    "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 238,"muscle_group": "Triceps","name": "Close-Grip Push-Up",                       "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 239,"muscle_group": "Triceps","name": "Dumbbell Kickback",                        "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 240,"muscle_group": "Triceps","name": "Dumbbell Overhead Tricep Extension",       "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 241,"muscle_group": "Triceps","name": "Dumbbell Tricep Press",                    "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 242,"muscle_group": "Triceps","name": "EZ Bar Overhead Extension",                "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 243,"muscle_group": "Triceps","name": "EZ Bar Skullcrusher",                      "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 244,"muscle_group": "Triceps","name": "Machine Dip",                              "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 245,"muscle_group": "Triceps","name": "Machine Tricep Extension",                 "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "S"},
    {"id": 246,"muscle_group": "Triceps","name": "One-Arm Cable Tricep Extension",           "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 247,"muscle_group": "Triceps","name": "One-Arm Dumbbell Overhead Tricep Ext",     "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 248,"muscle_group": "Triceps","name": "Resistance Band Tricep Pushdown",          "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 249,"muscle_group": "Triceps","name": "Rope Tricep Pushdown",                     "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 250,"muscle_group": "Triceps","name": "Seated Overhead Barbell Extension",        "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 251,"muscle_group": "Triceps","name": "Skullcrusher",                             "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 252,"muscle_group": "Triceps","name": "Tricep Bench Dip",                         "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 253,"muscle_group": "Triceps","name": "Tricep Pushdown",                          "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 254,"muscle_group": "Triceps","name": "Weighted Dip",                             "level": "Advanced",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 255,"muscle_group": "Triceps","name": "JM Press",                                 "level": "Advanced",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 256,"muscle_group": "Triceps","name": "Tate Press",                               "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 257,"muscle_group": "Triceps","name": "California Press",                         "level": "Advanced",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 258,"muscle_group": "Triceps","name": "Reverse Grip Pushdown",                    "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 259,"muscle_group": "Triceps","name": "Overhead Rope Extension",                  "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
    {"id": 260,"muscle_group": "Triceps","name": "Decline Skullcrusher",                     "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 261,"muscle_group": "Triceps","name": "Single Arm Overhead Extension",            "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 262,"muscle_group": "Triceps","name": "Two-Arm Overhead Extension",               "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 263,"muscle_group": "Triceps","name": "Tricep Dip Machine",                       "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "M",  "joint_type": "M"},
    {"id": 264,"muscle_group": "Triceps","name": "Body Weight Tricep Extension",             "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 265,"muscle_group": "Triceps","name": "Diamond Push-Up",                          "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 266,"muscle_group": "Triceps","name": "Decline Diamond Push-Up",                  "level": "Advanced",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 267,"muscle_group": "Triceps","name": "Band Tricep Pushdown",                     "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 268,"muscle_group": "Triceps","name": "Close Grip Dumbbell Press",                "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "M"},
    {"id": 269,"muscle_group": "Triceps","name": "Barbell Tricep Extension",                 "level": "Intermediate","body_region": "Upper", "push_pull": "Push",  "modality": "FW", "joint_type": "S"},
    {"id": 270,"muscle_group": "Triceps","name": "Straight Bar Pushdown",                    "level": "Beginner",    "body_region": "Upper", "push_pull": "Push",  "modality": "C",  "joint_type": "S"},
]

# ── Muscle group canonical name → tags for splits ──
MUSCLE_GROUP_TAGS = {
    "Chest - Pectoralis":           {"split": "push", "region": "upper", "primary": "chest"},
    "Shoulders - Delts/Traps":      {"split": "push", "region": "upper", "primary": "shoulders"},
    "Shoulders - Rotator Cuff":     {"split": "push", "region": "upper", "primary": "shoulders"},
    "Triceps":                      {"split": "push", "region": "upper", "primary": "triceps"},
    "Back - Latissimus Dorsi":      {"split": "pull", "region": "upper", "primary": "back"},
    "Back - Lat.Dorsi/Rhomboids":   {"split": "pull", "region": "upper", "primary": "back"},
    "Biceps":                       {"split": "pull", "region": "upper", "primary": "biceps"},
    "Lower Back - Erector Spinae":  {"split": "pull", "region": "core",  "primary": "lower_back"},
    "Legs - Quadriceps":            {"split": "legs", "region": "lower", "primary": "quads"},
    "Legs - Hamstrings":            {"split": "legs", "region": "lower", "primary": "hamstrings"},
    "Calves - Gastrocnemius":       {"split": "legs", "region": "lower", "primary": "calves"},
    "Calves - Soleus":              {"split": "legs", "region": "lower", "primary": "calves"},
    "Abdominals - Upper":           {"split": "core", "region": "core",  "primary": "abs"},
    "Abdominals - Lower":           {"split": "core", "region": "core",  "primary": "abs"},
    "Abdominals - Obliques":        {"split": "core", "region": "core",  "primary": "abs"},
    "Abdominals - Total":           {"split": "core", "region": "core",  "primary": "abs"},
}

# ── User target_muscle → muscle_group patterns ──
TARGET_TO_MUSCLE_GROUPS = {
    "chest":       ["Chest - Pectoralis"],
    "back":        ["Back - Latissimus Dorsi", "Back - Lat.Dorsi/Rhomboids", "Lower Back - Erector Spinae"],
    "shoulders":   ["Shoulders - Delts/Traps", "Shoulders - Rotator Cuff"],
    "arms":        ["Biceps", "Triceps"],
    "biceps":      ["Biceps"],
    "triceps":     ["Triceps"],
    "legs":        ["Legs - Quadriceps", "Legs - Hamstrings", "Calves - Gastrocnemius", "Calves - Soleus"],
    "quads":       ["Legs - Quadriceps"],
    "hamstrings":  ["Legs - Hamstrings"],
    "calves":      ["Calves - Gastrocnemius", "Calves - Soleus"],
    "core":        ["Abdominals - Upper", "Abdominals - Lower", "Abdominals - Obliques", "Abdominals - Total"],
    "glutes":      ["Legs - Hamstrings", "Legs - Quadriceps"],
    "full_body":   list(MUSCLE_GROUP_TAGS.keys()),
}

# ── Exercise search name map ──
SEARCH_NAME_MAP = {
    "Barbell Bench Press": "bench press",
    "Dumbbell Bench Press": "dumbbell bench press",
    "Incline Barbell Bench Press": "incline bench press",
    "Incline Dumbbell Bench Press": "incline dumbbell press",
    "Barbell Squat": "barbell squat",
    "Deadlift": "deadlift",
    "Romanian Deadlift": "romanian deadlift",
    "Pull-Up": "pull up",
    "Lat Pulldown": "lat pulldown",
    "Bent-Over Barbell Row": "barbell row",
    "Bent-Over Dumbbell Row": "dumbbell row",
    "Barbell Shoulder Press": "overhead press",
    "Dumbbell Shoulder Press": "dumbbell shoulder press",
    "Dumbbell Lateral Raise": "lateral raise",
    "Barbell Curl": "barbell curl",
    "Dumbbell Curl": "dumbbell curl",
    "Cable Tricep Pushdown": "tricep pushdown",
    "Rope Tricep Pushdown": "rope pushdown",
    "Dumbbell Lunge": "lunge",
    "Leg Press": "leg press",
    "Leg Extension": "leg extension",
    "Lying Leg Curl": "leg curl",
    "Seated Calf Raise": "seated calf raise",
    "Crunch": "crunch",
    "Front Plank (from toes)": "plank",
    "Push-Up": "push up",
    "Dips": "dips",
    "Goblet Squat": "goblet squat",
    "Bulgarian Split Squat": "bulgarian split squat",
    "Walking Lunge": "walking lunge",
    "Face Pull": "face pull",
    "Cable Row": "cable row",
    "Cable Fly": "cable fly",
    "Cable Lateral Raise": "cable lateral raise",
}

def get_search_name(exercise_name):
    return SEARCH_NAME_MAP.get(exercise_name, exercise_name.lower().replace("-", " ").replace("(", "").replace(")", ""))
